server: 
    port: 8080
    servlet: 
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring: 
    datasource: 
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:demo
        hikari: 
            username: sa
            password: 
    h2: 
        console: 
            enabled: true
    jpa: 
        hibernate: 
            ddl-auto: none #create update none
            naming: 
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties: 
            hibernate: 
                format_sql: true


#OAS
springdoc: 
    version: '@project.version@'
    api-docs: 
        path: /api-docs
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui: 
        doc-expansion: none
        operations-sorter: method
        tags-sorter: alpha
        path: /swagger-ui.html
        disable-swagger-default-url: false
        display-query-params-without-oauth2: true
        persist-authorization: true
    paths-to-match:
    - /api/v1/**
    - /test/**
