DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
		ID VARCHAR NOT NULL
	,	PASSWORD VARCHAR 
	,	NAME	VARCHAR
	,	AGE	BIGINT
	,	CONSTRAINT PK_USER PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS USER_DETAIL;
CREATE TABLE USER_DETAIL (
		ID VARCHAR NOT NULL
	,	MARKETINGYN	CHAR(1)
	,	MARKETINGDT	TIMESTAMP
	,	CONSTRAINT PK_USER_DETAIL PRIMARY KEY (ID)
	,	CONSTRAINT FK_USER_DETAIL_TO_USER FOREIGN KEY (ID) REFERENCES USER(ID)
);

DROP TABLE IF EXISTS USER_DELIVERY;
CREATE TABLE USER_DELIVERY (
		ID VARCHAR NOT NULL
	,	SEQ INT NOT NULL
	,	ADDRESS VARCHAR
	,	INSERTDT TIMESTAMP
	,	CONSTRAINT PK_USER_DELIVERY PRIMARY KEY (ID, SEQ)
	,	CONSTRAINT FK_USER_DELIVERY_TO_USER FOREIGN KEY (ID) REFERENCES USER(ID)
);